[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "cd week9-api-deployment && pip install --upgrade pip && pip install -r requirements.txt"
]

[start]
cmd = "cd week9-api-deployment && uvicorn app.main:app --host 0.0.0.0 --port $PORT"