[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "cd week9-api-deployment && python -m pip install --upgrade pip && python -m pip install -r requirements.txt"
]

[start]
cmd = "cd week9-api-deployment && uvicorn app.main:app --host 0.0.0.0 --port $PORT"